### ISSUE TITLE
Sorteringen endres ikke når ukedata først er lest inn

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#12]
Foreløpig baserer sorteringen seg på rekkefølgen i CSV-filen. Når denne først er lest inn av databehandler.py  endres den ikke i dictionary dersom rekkefølgen i CSVen endrer seg. Metadatene som distanse, tid etc blir oppdatert.

**Comment by thomiz** [comment]
Hvis vi lager funksjon som muliggjør dynamisk sortering av resultatlistene (tid, distanse, antall aktiviteter, navn) så løser vi vel denne også? Men det er antakelig en litt større jobb.

**Comment by xivind** [comment]
Fikset med [c09176e](https://github.com/hdir/strava-club/commit/c09176e6c56f6dce20831fa3dd50a54b3c47404d) Klar for review!

PS Yes, dynamisk sortering ville løst denne også, men det er som du sier en mye større jobb. Legger det som en egen issue - ny feature.

**Comment by thomiz** [comment]
Nydelig!
