### ISSUE TITLE
Lenke til strava klubben på resultatsiden

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#13]
* Legge til lenke til [strava klubben](https://www.strava.com/clubs/754665) for hdir
* Bør de akkumulerte resultatene for hele konkurranseperioden komme først på resultatsiden?
* Kan vi ta bort TTR Hdir fra resultatlistene, det er jo en ren administrativ konto. (Det løser seg kanskje av seg selv når vi nullstiller alt ved konkurransestart? jeg registrerer jo ikke noe aktivitet på den kontoen, gjorde det bare for å se hva som skjedde med aktivitetene når vi trodde vi skulle hente aktiviteter via API)

**Comment by xivind** [comment]
Lagt inn placeholder, men mangler tekst og lenke foreløpig.

**Comment by xivind** [comment]
@xivind legg inn teksten fra denne task: https://github.com/orgs/hdir/projects/3/views/1?pane=issue&itemId=55982544

**Comment by xivind** [comment]
PS @thomiz punkt 2, det skjer jo mest moro i tabellen for inneværende uke, så jeg foreslår den kommer først. Men jeg har ikke sterke preferanser. En mulighet kan jo være å ha inneværende uke først, så tabellen med data for hele perioden for alle utøvere, og etter det, tabeller for alle uker. Da er de to tabellene som stadig er i endring på topp, samtidig som vi får vist alle uker. Hva tror du om det? Til punkt 3, TTR Hdir vil forsvinne fra visningen når vi resetter ved konkurransestart (forutsatt at kontoen ikke logger aktiviteter).

**Comment by thomiz** [comment]
@xivind Bra at vi har fått plass til infotekst.

Men, vi må ha en egen side med informasjon om kampanjen, konkurranseregler osv, vi kan ikke ha dette på resultatsiden.
Vi kan ha en liten velkommentekst med lenke til strava klubben aller øverst (uten egen overskrift (tenker formatering som de akkumulerte resultatene) og lenke til informasjonssiden. Dette må vi få plass til på en vanlig linje for det er ikke det folk kommer for å se.

Det vanlige er jo å ha slik informasjon nederst på siden, men siden denne blir veldig lang tror jeg vi bør ha det øverst.

**Comment by xivind** [comment]
@thomiz enig, dette er et godt poeng! Den infosiden, blir det landingssiden, eller er results.html landingssiden, med lenke til infosiden derfra?

**Comment by xivind** [comment]
Så at du hadde svart på det allerede, results.html er landingssiden, med lenke til infoside. Lager som egen task en slik side.

**Comment by thomiz** [comment]
Resultatet er landingssiden tenker jeg?

tir. 12. mars 2024, 07:24 skrev Øivind Langeland ***@***.***>:

**Comment by xivind** [comment]
@thomiz takk for lenken til infosiden, og nå er teksten også formatert, ikke noe fancy, alt på en linje. Løst med denne [9130e3d](https://github.com/hdir/strava-club/commit/9130e3d6c9f811ebb60d97323a346fba97b6b1af) Klar for review.

**Comment by thomiz** [comment]
Det virker
