### ISSUE TITLE
Oppdatere results.html til å være responsivt design

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#15]
Det enkleste er kanskje å bruke et jekyll [tema](https://github.com/daattali/beautiful-jekyll)
* Det kan kanskje løse #19, #18 og forenkle #20

Men det er tabellene som er hovedsaken. Så da kan kanskje dette være en enkel [løsning](https://rickert-family.de/marcus/blog/responsive-tables-in-bulma), hvis vi går for jekyll for eksempel.

**Comment by xivind** [comment]
Jeg må se mer på det senere, men det Jekyll-alternativet du viste til virker MEGET interessant (og overkommelig), særlig i kombinasjon med rickert-familyls hack! Da det er sagt, det vil nok kreve litt eksperimentering, så foreslår å lage info-siden på gamle-måten nå, det er fort gjort, så vi får den opp.

**Comment by xivind** [comment]
Denne løses i sammenheng med #22

**Comment by thomiz** [comment]
Løst med Just the docs
