### ISSUE TITLE
Lag logo til bruk i Github-teamet og eventuelt andre steder

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#16]
Vi ønsker en logo vi fritt kan bruke, blant annet på badgen for Github-teamet som driver utviklingen av produktet. Kanskje kan også logoen vises på results.html. [playground.ai](https://playgroundai.com/) kan brukes for å lage logoer.

**Comment by thomiz** [comment]
Ja, jeg har lagt til en logo, men den er ikke AI generert...

**Comment by xivind** [comment]
Logoen er utmerket og det har ingen betydning at den ikke er AI-generert. Lukkes.
