### ISSUE TITLE
Rydd i CSS

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#19]
CSS-filen må gjennomgås og ryddes. Gjør det enklere å ha kontroll på formateringen. Også en god forberedelse til tasken om å legge over til responsivt design: https://github.com/orgs/hdir/projects/3/views/1?pane=issue&itemId=55990531

**Comment by xivind** [comment]
Denne løses i sammenheng med #22

**Comment by thomiz** [comment]
Løst med just-the docs
