### ISSUE TITLE
Tid i minutter i resultatlisten

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#2]
Vi ønsker oss tid i minutter, kanskje også tre kategorier, over 300 minutter, over 150 minutter (Helsedirektoratets anbefaling om fysisk aktivitet i uken) og under 150 minutter. De som ikke oppnår 150 minutter i uka mister den ukens "lodd" tenkte jeg var en grei plan i forbindelse med trekninger.

**Comment by xivind** [comment]
Databehandler.py er oppdatert med ny kode slik at vi nå beregner og tar vare på lodd pr uke, jf. beskrivelsene som stod i en annen issue: 150-299 minutter pr uke = 1 lodd, 300 og over = 2 lodd og alt under 150 er ingen lodd. Skal oppdatere presentator.py slik at oppnådde lodd vises i tabellen, ved siden av minuttene kanskje?

**Comment by xivind** [comment]
Mens dette løses, se samtidig på funksjonen format_duration i presentator. Det er noe galt med funksjonen. Den bør returnere hh:mm, evt. bare minutter. Husk at data fra Strava kommer som sekunder.

**Comment by xivind** [comment]
Setter denne til høy fordi det er forvirrende og upresist slik beregningen er nå, jf. f. eks 0 timer ved ukestart, selvom tid har påløpt.

**Comment by xivind** [comment]
Dette er nå ordnet med [0670d41](https://github.com/hdir/strava-club/commit/0670d415f6e3131f1032721ff1525bfa63f2b78b) Billetter legges automastisk til i uke-kolonnene, slik om nevnt over, og tid vises i formatet tt:mm. Denne saken er klar for review!

Totalt antall billetter pr person for hele perioden håndteres i egen issue #17, foreløpig kun backlog, men dataene har vi .

**Comment by thomiz** [comment]
Review OK
