### ISSUE TITLE
Lage infoside

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#20]
Se mer om innhold og lenking til infosiden: https://github.com/orgs/hdir/projects/3/views/1?pane=issue&itemId=55982542

**Comment by xivind** [comment]
@thomiz legger til deg også på denne, for det må vel gjøres noe i action-scriptene her slik at info.html kopieres til data/results mappen?

**Comment by thomiz** [comment]
info.html legges i samme mappe som results html, altså *web*.

**Comment by xivind** [comment]
Selvsagt, det fikser jeg!

**Comment by xivind** [comment]
Infosiden er laget med teksten fra #4 , også lagt inn lenke til resultatsiden, og til alt overmål er infosiden i responsivt design.. Klar for review!


![Image](https://github.com/hdir/strava-club/assets/8987107/13a44b2a-bbdc-4cdf-836a-4863014e1f54)



![Image](https://github.com/hdir/strava-club/assets/8987107/d5cbbea0-aad9-4894-a503-7e51437155f3)

**Comment by thomiz** [comment]
Den er OK
