### ISSUE TITLE
results.html og css duplikater

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#21]
Vi må bestemme oss for hvor css filen skal ligge. Nå ligger den både i web/static og /static.
results.html er ikke en statisk fil men genereres hver gang scriptet kjøres, denne bør slettes fra repo.

**Comment by xivind** [comment]
@thomiz  CSS: for meg er det enklest hvis den ligger i /static, men det var noe med at vi kopierte den til web/static for at den skal være tilgjengelig for results.html? Du kan bestemme, gjør det du mener er best og slett den andre. Bare si fra før du gjør det, så jeg kan committe det jeg holder på med. Skjer noe hele tiden :)

Results.html: helt enig, bare sløvt av meg. Jeg lager den lokalt mens jeg tester og så har jeg glemt å slette før jeg comitted. Slettet nå.

**Comment by xivind** [comment]
@thomiz gikk for å beholde den i web/static siden det er den som leses, hvertfall når man åpner results fra main branch. Kan du sjekke at det er den fra web/static som også kopieres inn til gh-branches? I så fall kan denne saken lukkes. Results.html er allerede slettet fra roten. Det betyr også at vi kan slette denne delen av koden fra presentator.py:
`# Copy static css to web directory - not needed, original is in web/static
#shutil.copyfile('./static/styles.css', './web/static/styles.css')`

**Comment by xivind** [comment]
Denne CSSen web/static brukes vel ikke lenger og kan slettes?

**Comment by thomiz** [comment]
Enig, slettet hele web katalogen som nå er overflødig.
