### ISSUE TITLE
Feil i presentator.py

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#25]
Kjøringen stopper pga ny bug i koden. Se siste schedulerte kjøring.

**Comment by xivind** [comment]
Er på saken!

**Comment by xivind** [comment]
Hadde glemt noen \ i forbindelse med placeholder for nye datafelter aggregerte data. I orden nå, funker hos meg, som det heter på fint. Klar for review!

**Comment by thomiz** [comment]
Det kjører, men ser ikke helt riktig ut?


![Image](https://github.com/hdir/strava-club/assets/6229665/d9c26da6-ef7f-412c-920c-13f37fd73be2)

**Comment by xivind** [comment]
Det er riktig, mangler noen beregninger. Bare la ut placeholdere foreløpig. Datatfeltene kommer i løpet av kvelden. La oss ha denne saken åpen foreløpig. PS Si fra om du vet om den beste måten å regne CO2..

**Comment by thomiz** [comment]
Hva med layouten? Skal de ikke komme etter hverandre?

**Comment by xivind** [comment]
Sykt at jeg ikke så det, tenkte ikke over det, var bare opptatt av det stod 0 og at dataene skulle komme etterpå. Hvert fall fikset nå. Hadde med noen <tr> for mye..

**Comment by thomiz** [comment]
DONE
