### ISSUE TITLE
Oppdatere presentator.py for Just-the-docs

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#26]
**Oppdateres i [test branch](https://github.com/hdir/strava-club/tree/test)**
Jeg trenger oppdatering av presentator.py slik at det produseres filer som kan leses av Just-the-docs.
1. presentator må lage en fil for resultater som ligger i rotkatalogen og heter index.md
2. index.md må inneholde frontmatter som ligger i denne variabelen.
~~~ 
[FRONTMATTER]
RESULTS = '---
layout: default
title: Resultater
nav_order: 1
---'
~~~

**Comment by xivind** [comment]
Dette høres greit ut @thomiz , men jeg skjønner ikke hvorfor presentator må lage info-filen. Det er jo en statisk fil som jeg trodde du skulle skrive i markdown, jf. #22 , og at det var det vi trengte der. Eller misforstår jeg noe her?

**Comment by thomiz** [comment]
Bare surr fra min side. Den er jo statisk 🤦‍♀️
Jeg oppdaterte beskrivelsen

**Comment by xivind** [comment]
@thomiz , del 1 og 2 av denne oppgaven er gjort og dyttet til testbranch. Avventer del 3 og 4 inntil jeg hører fra deg. Lurer som sagt på hvorfor vi må få presentator til å produsere en fil (info.md) som kun har statisk innhold. Mulig jeg overser noe?

**Comment by xivind** [comment]
Nydelig @thomiz , i så fall er denne klar for review! Men en ting. Vi har gjort masse endringer i presentator siden denne branch ble opprettet, så best om ikke testbranch presentator overskriver mainbranch presentator. Men det hadde du kanskje ikke tenkt heller? Og siste spørsmål, jf. tittelen på oppgaven, ser ikke at det er noe vi trenger å gjøre i databehandler.py her? Den produserer jo ikke noe som skal vises 🤔

**Comment by thomiz** [comment]
@xivind Alle scriptene (og data) skal være helt oppdatert i forhold til det som finnes i main, jeg har dratt endringer fra main til test tidligere i dag. Og gjorde det igjen nettopp nå uten konflikter.

**Comment by xivind** [comment]
Perfekt, tusen takk, da er alt i orden! Er vi klare til å merge? Jeg har gjort endringene på min kant hvert fall. Dette ble en mye bedre løsning denne den vi hadde.

**Comment by thomiz** [comment]
Det er et problem fordi vi får en tom linje i starten av results.md og da forstår ikke jekyll fila og lager en dustefil som ikke kan vises riktig.
https://hdir.github.io/strava-club/TestBuildJTD/index.html

Er det noen måte å ikke få en newline i starten [der](https://github.com/hdir/strava-club/blob/gh-pages/TestBuildJTD/index.md)? @xivind

**Comment by thomiz** [comment]
Hmm, kanskje jeg bare kan slette den :-)

**Comment by xivind** [comment]
Funket det å bare slette den @thomiz ? Hvis ikke si fra, jeg vet ikke hvordan, men det finner jeg ut av, om du ikke allerede har løst det.

**Comment by thomiz** [comment]
DONE
