### ISSUE TITLE
Simulere aksjonsstart og fremprovosere feil

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#29]
Vi må teste at produktet fungerer når man tømmer results.json og begrenser input til databehandler.py til en uke. Foreløpig mangler funksjonen i databehandler.py for å filtrere på uker. Foreslår vi lager den metoden som del av testen. Stor sannsynlighet for at det meste av metoder i databehandler.py og det meste av funksjoner i presentator.py vil krasje dersom det ikke er noe data. Jeg tenker vi kan leve med det, men koden må kunne håndtere at det kun kommer data for én uke. Evt. kan vi legge inn en sjekk i begynnelsen av begge script som hopper over metode- og funksjonskall dersom results.json er tom. Til diskusjon.

**Comment by thomiz** [comment]
Lager du en egen branch for det? Jeg tror vi har må ha feature frys for andre endringer i scriptene når vi starter på denne slik at merging ikke blir for vanskelig. Foreslår at vi lager totalt antall lodd først #17

**Comment by xivind** [comment]
Enig, la oss ta både antall lodd #17 og flammen #30 før feature frys, sistnevnte er bare 5 min ekstra.

**Comment by thomiz** [comment]
Gjennomført, og feil funnet.
1. Databehandler krever at results.json eksisterer.
2. Et par feil rettet i skraperen.
3. Prosedyre beskrevet i #34

**Comment by xivind** [comment]
Takk som testet @thomiz Funn nr. 1 der har vi jo nå en egen issue på #39 , det fikser jeg. Nr 3 kan vi løse ved å legge inn teksten du skrev  i #34 i readme-filen. Jeg fikser det etterpå.
