### ISSUE TITLE
Oppdatere infosiden med beskrivelse av hva ikonene på resultatsiden betyr

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#31]

**Comment by xivind** [comment]
Infosiden er oppdatert med følgende ikonforklaring. Tar du en titt og justerer slik du synes passer @thomiz ? Prøvde å gjøre det kort og trivelig.

![Image](https://github.com/hdir/strava-club/assets/8987107/87184899-93d6-4909-aaad-08077f67746e)

**Comment by thomiz** [comment]
God som gull 👍
