### ISSUE TITLE
Rydd opp i HTML-kode i presentator

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#36]
Div-blokkene i html-koden inneholder gamle klassereferanser og bør "vaskes". IDene er antakeligvis ok fortsatt, men bør sjekkes for konsistens. Brukes ikke til noe.

**Comment by xivind** [comment]
Løst i presentator V2, hadde ingen praktisk betydning. Trengs ikke å løses i gammel presentator.

**Comment by thomiz** [comment]
Bra! Hvordan tester vi denne @xivind . Burde vi hatt det i en test-branch?

**Comment by xivind** [comment]
Ooops, ser ut som just-the-docs plukker opp alt som heter .md og putter inn i visningen sin, så disse filene som presentatorV2 lager, uten klassereferanser for div-blokkene virker tydeligvis og er allerede publisert. Ser helt like ut som de andre formateringsmessig.  Kanskje du kaster et blikk på det, og dersom du synes det er greit kan denne saken stenges. Og så sletter vi alle md-filene fra repoet, bortsett fra index.md. Jeg skal passe på å ikke dytte arbeidskopiene mine opp når du har sjekket ut denne.

**Comment by thomiz** [comment]
Det som ikke skal ut på web ekskluderes enkelt i _config.yaml.

**Comment by xivind** [comment]
Nyttig, skal gjøre det om jeg fortsetter å teste med de filene!

**Comment by thomiz** [comment]
Det er lagt inn i yaml, men evt. nye filer må du huske å nevne i exclude @xivind

**Comment by xivind** [comment]
Ypperlig, takk @thomiz , det er notert!
