### ISSUE TITLE
Juster purge-funksjonen for å også inkludere stopp-dato for aksjone

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#37]
Endre fra '<' til 'in range(STARTWEEK, STOPWEEK+1)' Første parameter er inkludert i telling, siste er ekskludert, derfor må det plusses på 1.

**Comment by xivind** [comment]
Nå slettes aktiviteter både før og etter kampanjeperioden. Har testet litt frem og tilbake, og ser ut som det funker, men litt vanskelig å teste skikkelig fremover i tid, selv om test med uke 12 viser at det nok funker. For denne testperioden vi er inne i nå satte jeg stoppuken til uke 13. Range funksjonen inkluderer gulvet, men ikke taket, derfor plusser vi på en uke på kampanjestopp. Kan du ta en titt @thomiz  og se om det er noe i logikken du stusser på? Dette ligger altså i databehandler i purge-funksjonen:


![Image](https://github.com/hdir/strava-club/assets/8987107/c9061a99-1bfb-45ed-9f9f-a79af31194c7)

**Comment by thomiz** [comment]
Den ser god ut, og det fungerer for kampanjestart, så ser vi med kampanjeslutt. Har vi satt en kampanjeslutt for prøvekampanjen (som vi er inne i nå?).

**Comment by xivind** [comment]
Yes @thomiz vi har satt at andre prøveperiode går fra uke 12-14 (kommer først inn når du merger pull request). Da får vi testet tre uker. Denne informasjonen settes nå i konfigfilen. Da lukker jeg denne. Åpen igjen om du er uenig.
