### ISSUE TITLE
Utvid datastore med to nye nøkkelpar for å gjøre klar for lag

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#38]
Legge til følgende to nøkler i datastore:
"team":"",
"athlete_id";"athlete_id"

@thomiz Jeg foreslår å legge til disse to nøklene over i datastore i databehandler. Det tar fem minutter og har ingen ringvirkninger, men det vil gjøre ting veldig mye enklere for oss om vi ser at vi får til det med lagdeling i MVP, enten via Strava Clubs eller FastAPI. Dersom vi ikke får det til blir nøkene bare liggende ubrukt og gjør ingen skade og skaper heller ikke ekstra kompleksitet. Men prinsipielt synes jeg vi skal være enstemmig på endringer i hoveddata-modellen vår. Kan du gi en tommel opp om dette er ok for deg? Eller noe annet om du har innvendinger. PS Jeg vet fokuset vårt er på MVP, men dette tar som sagt 5 min, og det er fakta, og det vil betale seg.

**Comment by xivind** [comment]
Diskutert i teamet, enstemmig vedtatt, sett i gang 👍👍

**Comment by xivind** [comment]
De to ekstra nøkkelpar er lagt inn @thomiz , tok en liten prøvekjøring lokalt og som forventet (på akkurat denne) var det ikke noe havari. Vi bruker ikke disse feltene til noe p.t, men dersom vi en vakker høstdag skulle få team og vi fortsatt skrur på denne prototypen er hvert fall alt klart. Slik ser strukturen ut nå. For sikkerhetsskyld setter jeg denne til review, men tror den er ok.


![Image](https://github.com/hdir/strava-club/assets/8987107/f7ebc3b3-25e7-4c20-9c4c-f2e3f6110a2e)

**Comment by thomiz** [comment]
Dette virker jo bare.
