### ISSUE TITLE
Databehandler krasjer når results.json mangler ved starten av en konkurranseperiode

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#39]
Se kjøring: https://github.com/hdir/strava-club/actions/runs/8322646077/job/22770796495

Denne haster det litt med...

**Comment by xivind** [comment]
Bra oppdaget @thomiz . Det kan ligge flere slike påskeegg rund omkring i koden, så vær på utkikk 🪲🐛 Slik ser justert kode ut. Kan du se at du synes logikken ser riktig ut:


![Image](https://github.com/hdir/strava-club/assets/8987107/de94a76f-1eab-49c0-b31c-b00d543c4800)

**Comment by thomiz** [comment]
Den er god
