### ISSUE TITLE
Beskrive konkurranseregler og hvordan man deltar i konkurransen.

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#4]
1. Bli medlem i [hdir strava klubben](https://www.strava.com/clubs/754665)
2. Registrere aktiviteter i strava, enten automatisk eller manuelt i Strava appen(*).
3. Vinn fine premier 🥇 

Beskrivelse av konkurransereglene:
1. All aktivitet telles i sammendraget.
2. 1 lodd tildeles hver uke for de som har mer enn 150 minutter aktivitet i uken.
4. 2 lodd tildeles for de som har mer enn 300 minutter aktivitet i uken.
5. Alle lodd er med alle trekningene. Man kan maksimalt bli tildelt 16 lodd i løpet av konkurranseperioden som går over 8 uker.
6. Det er en trekning etter to uker og tre trekninger ved konkurransens slutt.

(*) ved manuell registrering i Strava appen deles ingen lokasjonsdata med Strava eller Strava sine brukere. Ved automatisk registrering med GPS spor i app/device kan lokasjonsdata beskyttes ved å bruke en privat Strava konto.

**Comment by thomiz** [comment]
@xivind la til funksjon for å regne antall lodd inneværende uke.

Behov: Totalt antall lodd i løpet av perioden som en del av den siste tabellen.

**Comment by xivind** [comment]
@thomiz god beskrivelse, lagt inn på infosiden, med noen mindre endringer. Ingenting endret på meningsinnhold.   Jeg stenger denne saken her nå, så kan review skje via saken om lage infoside #20 . Totalt antall lodd i løpet av perioden, jf. kommentar over, løses i egen sak #17
