### ISSUE TITLE
Ta den statiske delen av resultatsiden ut av presentator scriptet

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#40]

**Comment by xivind** [comment]
Løs ved å lagre velkomstmeldingen i en variabel i konfigfilen, og så hente den hver gang siden lages.

**Comment by xivind** [comment]
Spørsmål til denne issue @thomiz  Skal jeg legge en svak grå bakgrunn eller noe på den brukerdefinerte teksten slik at den liksom skiller seg litt ut? Eller vil vi bare ha den helt plain som et eget avsnitt?

**Comment by xivind** [comment]
Da er denne fikset @thomiz  Ser slik ut, se under. Foreløpig ligger teksten i en variabel i toppen av presentator_V2.py, men den variabelen skal få sin verdi fra konfigfilen når jeg fikser #5 Variable filstier.. Dersom denne variabelen er tom vil ingenting vises, heller ikke den grå bakgrunnen selvsagt. Dersom vi vil ha annen formatering kan vi bare justere rett i html-koden i presentator. Jeg tenker på formatering som statisk og ikke noe som trenger å ligge i konfig.ini. Se under for koden (både sjekken og formateringen). Med andre ord, klar for review :) PS Tok sjansen på å kjøre deploy-scriptet manuelt for å se hvordan det ser ut live.

![Image](https://github.com/hdir/strava-club/assets/8987107/e70b7b51-1b79-4261-a425-00ea0b5d0b48)


![Image](https://github.com/hdir/strava-club/assets/8987107/4171e5b4-891e-4a4c-9a01-9da1eb0f1aa2)

**Comment by thomiz** [comment]
Ser jo bra ut!
