### ISSUE TITLE
CO2 spart tallet er feil

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#41]
![Image](https://github.com/hdir/strava-club/assets/6229665/694acdf0-6e8a-4091-bdce-3a2d32b05b48)

Dette tallet ser helt feil ut, spesielt sammenlignet med Strava tallet for CO2 spart.

![Image](https://github.com/hdir/strava-club/assets/6229665/9bbba142-c132-40d1-ac04-78bc7a29b261)

**Comment by xivind** [comment]
Feil og feil.. Det er lavere og mer konservativt enn Stravas, men det kommer vel bare an på hvilket tall vi legger til grunn. Vi baserer oss på tallet fra European Cyclist Feederation, som er 16g https://ecf.com/news-and-events/news/how-much-co2-does-cycling-really-save Tror Strava bruker c02 fra bil, som er 240g eller noe. Bare si fra hvilket du vil ha @thomiz , så kan vi bruke det, men greit å ikke smøre altfor tjukt på..

**Comment by xivind** [comment]
Eller har jeg med enn 0 for mye her?

def calculate_co2_saved(self, distance_km):
        """Method to calculate saved co2 pr km"""
        return round(distance_km*0.016, 2)

**Comment by xivind** [comment]
Ved nærmere ettersyn, det tallet er riv ruskandes galt.. Nytt forslag: Utslipp bil pr km 271g (https://ecf.com/news-and-events/news/how-much-co2-does-cycling-really-save) Utslipp sykkel kan sikkert regnes på forskjellige måter, men la oss si 51g pr km  (det er omtrent dobbel så mye som det ECF sier), da sparer vi 220g c02 pr km, og får et tall for spart utslipp som likner på Strava. Skal vi går for den? Gi beskjed, så fikser jeg, tar akkurat 60 sek.

**Comment by xivind** [comment]
Rettet fra 16g til 220g. Kan du sjekke formelen @thomiz , det er tydeligvis behov for doble øyne på matematikken min..  Slik ser det ut nå:
`def calculate_co2_saved(self, distance_km):
        """Method to calculate saved co2 pr km"""
        return round(distance_km*0.220, 2)`

**Comment by thomiz** [comment]
Det blir riktig!
