### ISSUE TITLE
Første dag i kampanjen bør stjernemerking ikke benyttes?

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#42]
Alle utøvere får stjernemarkering den første dagen, det gir kanskje ikke så mye verdi?

**Comment by xivind** [comment]
Jeg personlig likte stjernene, som et slags velkommen til kampanjen, men ser også ditt poeng! Rankingfunksjonen er modifisert slik at det ikke vises symboler i første uke. Det er denne setningen som sørger for det `if int(CAMPAIGN_WEEK_START) == int(toolbox.get_current_week_number()):
                rankings.update({value["athlete_name"]: ""})`

Alt ligger i funksjonen `get_changed_ranking(self)` Tar du en kjapp titt @thomiz  og lukker dersom du synes logikken stemmer? Har testet og ser riktig ut, men godt med to par øyne, alltid!

**Comment by thomiz** [comment]
Med nærmere ettertanke er det kanskje bare den aller første dagen vi ikke skal ha stjerner? Vet du hva, jeg tror vi egentlig bør fjerne denne logikken. Det er jo dumt om vi ikke skal ha stjernemarkering den første uken. Jeg tror du har rett: "personlig likte stjernene, som et slags velkommen til kampanjen". 

Du bestemmer, om vi skal gjøre det om eller ikke @xivind

**Comment by xivind** [comment]
Takk @thomiz Da velger jeg at stjernene kommer tilbake, siden jeg liker litt slike ting, og dessuten stemmer da brukerdokumentasjonen vår, nemlig: at nye utøvere er stjernemarkert ⭐. Det ekstra filteret er fjernet, og logikken er nå slik den var før. Tidligere reviewet, derfor stenger jeg denne nå.
