### ISSUE TITLE
Feil i avrunding på distanse (for mange desimaler)

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#44]
Ser ut som det kun er avrunding i aggregerte resultater, og at det mangler i ukeresultater og resultater for hele perioden. Oppdater tabellene med denne koden `round([data], 1)` 

![Image](https://github.com/hdir/strava-club/assets/8987107/9dca9314-8e50-4e3e-844e-6da9497197b7)

@thomiz , litt rart at denne bug ikke kom til overflaten i prove 1 🤔 Kommer snart til review. Fikser den i branch issue-5, samtidig med variabler i konfig-fil.

**Comment by xivind** [comment]
Denne er løst, og fiksen ligger i den PR som er åpen. Løste ved å bruke round(data, 1) i HTML, tabellene, slik at rundingen kommer helt til slutt.

**Comment by thomiz** [comment]
OK
