### ISSUE TITLE
Review oppdatert infoside

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#45]
Oppdaterte siden, trenger review https://hdir.github.io/strava-club/CurrentBuild/docs/info.html

**Comment by xivind** [comment]
Så på infosiden nå. Bra du har lagt den over til markdown. Ellers fine tillegg, likte spesielt presiseringen til at data må registreres innen to uker, og det om privacy settings. Gjorde noen små endringer her og der, blant annet denne:
All aktivitet teller i sammendraget > All aktivitet teller .

Kanskje du ser over mine endringsforslag, og enten avviser eller tar inn, etter det kan denne saken stenges for min del.

**Comment by thomiz** [comment]
OK
