### ISSUE TITLE
Bilde og beregning på toppen av side som viser antall ganger tur-return Lindesnes

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#47]
Inspirert av det du skrev i Iris-teksten @thomiz  Hadde det vært kult å hatt et lite ikon som symboliserer Lindesnes-Nordkapp og så et løpende oppdatert tall under / ved siden av som viser hvor mange ganger frem og tilbake aksjonen samlet har vært? Bare en tanke. Setter den på lav prioritet foreløpig, altså utenfor MVP inntil vi har realitetsbehandlet..

**Comment by thomiz** [comment]
Enig, kunne hatt en for jorda rundt (ca 40 000km) og en for lindesnes nordkapp (ca 3000km)?

**Comment by xivind** [comment]
Yes, god ide! Jeg begynner å tenke litt å dette. Hadde jo vært kult å hatt noe litt visuelt, en progress bar eller noe slikt. Skal tenke litt på det, kommer tilbake.

**Comment by thomiz** [comment]
I MVP v1 kan vi jo bare sette inn ett en ny rekke med tall i akkumulert tabellen med et symbol med jordkloden/norge hvor tallet baserer seg på antall kilometer for klubben og delt på 3000/40000? 🌍 
![image](https://github.com/hdir/strava-club/assets/6229665/8d0e2278-8711-487b-8806-75c95d5b3f32)

**Comment by xivind** [comment]
Det var en god ide, vi prøver oss på noe slikt! Vi har allerede en dev-branch. Jeg foreslår at vi lar den være permanent, så bruker vi den for å teste ut blant annet slike ting. Gir beskjed når jeg har noe klart her.

**Comment by xivind** [comment]
@thomiz , noe slikt?



![Image](https://github.com/hdir/strava-club/assets/8987107/a2b59806-a138-4c75-8125-af4ff7ef8029)

**Comment by xivind** [comment]
PS Fjernet desimaler på km og co2 også. Ikke gjøre en pull på dette enda. Må se på det med et litt mer våkent øye. Jeg tipper det må være noe feilhåndtering her, siden deling på 0, som det vil være første dagen, sjelden pleier å ende godt..

**Comment by thomiz** [comment]
Ser veldig bra ut @xivind 👍

**Comment by xivind** [comment]
@thomiz litt hjelp til matten her, beregningen for disse to tallene ser ut som dette:

- {round(int(self.results.aggregated_summary['distance'])/2318, 1)} ganger Lindesnes - Nordkapp
- {round(int(self.results.aggregated_summary['distance'])/40075, 1)} ganger rundt jorden

Jeg mener vi ikke trenger noen feilhåndtering på dette fordi det det bare er deling på 0 som gir feil. Men i koden over deles det aldri på null, selv om tilbakelagt distanse er 0. Enig?

**Comment by thomiz** [comment]
Enig, 0 delt på noe blir 0 det også.

**Comment by xivind** [comment]
Den er god, lagde en PR nå

**Comment by thomiz** [comment]
Vi er i prod.

**Comment by xivind** [comment]
Nydelig 👍👍
