### ISSUE TITLE
URL for resultatsiden

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#48]
Hvilken url vil vi ha:
* Utviklingsversjonen ligger her: https://hdir.github.io/strava-club/CurrentBuild/
* Vi kan ha det her: https://hdir.github.io/strava-club/
* Eller for eksempel sånn: https://hdir.github.io/strava-club/vaar24

Det enkleste administrasjonsmessig vil være "vaar24".

**Comment by xivind** [comment]
@thomiz dette er bra å få fikset, og midt i blinken dersom vi kan ha en parallell versjon for utvikling. Jeg stemmer for at vi går for det som er enklest administrasjonsmessig, altså vaar24. Fikser du?

**Comment by thomiz** [comment]
Da er resultatene flyttet
