### ISSUE TITLE
Endre variable for filstier og andre konfigurasjonsparametere fra hardkoding til å lese fra konfigurasjonsfil

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#5]
Vi ønsker å unngå hardkoding og gjøre det lett å endre stier og filnavn uten å ødelegge noe (og uten å endre det 100 steder)

Gjelder disse filene:

- [ ] strava-club-scraper.py
- [ ] databehandler.py
- [ ] presentator.py

**Comment by xivind** [comment]
Påstand: ikke viktig for MVP. Si fra om du er uenig @thomiz .

**Comment by thomiz** [comment]
Delvis enig, men start og stopptid for konkurransen mener jeg bør leses fra config som et minimum.

**Comment by xivind** [comment]
Den er grei, det fikser jeg 👍 Spørsmål, da tar vi den helt ut og hardkoder heller ikke konfigurasjonsfilen? Den må i så fall gis som et parameter når pythonscriptene starter og da må vel action-scriptene endres. Med det gjør ikke noe vel? Er bare å snakk om å legge til "--configfile konfigurasjonsfil". Kunne vært fint for meg å forstå de action-script bedre, så kanskje vi kan fikse det sammen.

**Comment by xivind** [comment]
Tenkte å titte litt på denne i kveld @thomiz Og her er sjansen stor for breaking changes.. 😮 Jeg jobber derfor med dette i egen branch, så kan vi merge når jeg er ferdig og du har tatt review.

**Comment by xivind** [comment]
Strevde litt med å få det til å funke når jeg bruker [AKSJON] seksjonen, så måtte faktisk lage en ny seksjon. Konfigurasjonen som brukes av databehandler og presentator ligger nå i CAMPAIGN. Turte ikke å endre AKSJON. Fant ikke noen steder den brukes i skraperen, og jeg vet den ikke brukes av databehandler og presenator, men antar den har en funksjon et eller annet sted.. Den scraperen er for øvrig vilt komplisert. Prinsipielt er jeg ikke så glad for å skru på ting hvor jeg ikke hvert fall har en slags røff forståelse av hvordan helheten er, og den scraperen er en svart boks for meg. Med sine 2400 linjer er det mye som tyder på at det vil fortsette å være slik en stund. Men uansett, kortversjonen, alt av brukerkonfigurerbare variabler i databehandler og presentator_V2 styres nå fra konfigfilen, inkluder info_beskjed til brukere. Din bestilling var i utgangspunktet minimum start og stopp dato kampanje, samt info_beskjeden, så da anser jeg denne saken som sjekket ut, og at det er greit at vi har hardkoding i scraperen. Håper du også kan leve med det, og at vi kan stenge saken etter din review. Jeg har selvsagt testet, og det ser greit ut, men se på det du også. Særlig at start og stopp-datoene kommer på rett sted. 

![Image](https://github.com/hdir/strava-club/assets/8987107/987f51a9-c158-4fe5-9de5-eb8fa05afaa1)

**Comment by thomiz** [comment]
Ser ut ti lå fungere
