### ISSUE TITLE
Oppdatert tekst til resultatsiden

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#55]
Vi trenger en ny infotekst på toppen nå som aksjonen er i gang.

Tenker informasjon om hvor ofte det kjører er mest relevant.

**Comment by thomiz** [comment]
Forslag:
> Aktivitetsaksjonen er nå i gang (15. april - 9. juni). Resultatsiden oppdateres 4 ganger i døgnet (kl 09, 11, 18 og 00).

**Comment by xivind** [comment]
Forslaget er utmerket @thomiz og jeg har ingen merknader 👍

**Comment by thomiz** [comment]
Da er det oppdatert.
