### ISSUE TITLE
Generere liste for loddtrekning

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#57]
Basert på resultatene fra aksjonen. Trekningslisten må inneholde en linje pr lodd, n er antall lodd totalt tildelt gjennom perioden:

> 'Loddnummer(løpenummer) - Deltakernavn [linjeskift]'

Eksempel:

> 1 - Thomas Rosenlund
> 2 - Øivind Langeland
> ...
> n - xxx

**Comment by xivind** [comment]
@thomiz første versjon er klar! Outputen er som spesifisert i oppgaven. Tid er en kostbar ressurs, så på dette scriptet foreslår jeg vi gjør det enkelt  og dropper både funksjons- og objektorientering, samt feilhåndtering. Tenker det er ok siden det kun skal kjøres manuelt og det er så få kodelinjer. Har lagt inn noe enkel statistikk så vi kan gjøre en slags enkel manuell kontroll, og kanskje morsomt å skrive noe om det etter hvert også på Iris. Koden ligger i dev-branch. Kan du teste og se på det?

PS Scriptet overskriver ut-filen hver gang det kjøres. Vi burde antakeligvis gjøre det mulig å spesifisere hvilke uker vi vil beregne lodd for.  Har lagt inn placeholder for variabel, men ikke implementert foreløpig. Vil vi ha det? I så fall, gi beskjed, så fikser jeg.


![Image](https://github.com/hdir/strava-club/assets/8987107/47127a3e-56dc-48b7-8101-36d735d8196a)


![Image](https://github.com/hdir/strava-club/assets/8987107/7aad9232-16fb-4b7b-a167-9def5b0939a2)

**Comment by xivind** [comment]
PS Sov på det med statistikk, og det er litt mer koding som må til enn det jeg trodde. Stemmer derfor for å droppe det, evt. flytte det til en issue med lav prioritet..

**Comment by thomiz** [comment]
Det er en bug her når man genererer for uker som ikke finnes i results.json får man likevel generert loddliste med lodd tildelt.

**Comment by xivind** [comment]
Ny versjon klar @thomiz Filtrering på uke er nå på plass. Tar du en titt og merger om du synes det ser greit ut?
**Detaljer:**
Juster dette parameteret her før loddtrekning  (ligger i toppen av lodd_generator.py) `TICKET_WEEKS = [16, 17]` På sikt kan vi flytte dette parameteret, og parameter for utfilen til konfig.ini. Men som nevnt best å ikke klusse med det nå siden det er noe med den konfig.ini filen jeg ikke forstår som gjør at det å legge til nye parameter kan føre til at andre parametere ikke blir lest. Lager en egen issue på det og legger den inn i backlog, så kan vi fikse det når aksjonen er over.

**Comment by thomiz** [comment]
Gått igjennom, kontrollert og merget til master.
