### ISSUE TITLE
Resultatlisten er ikke lesbar på mobil

### ISSUE THREAD

**Issue by thomiz** [hdir/strava-club#6]
Formateringen tilpasser seg ikke til smale skjermer.

**Comment by xivind** [comment]
Denne her er vanskelig, dersom vi skal løse det med fullt ut responsivt design.  Kanskje vi for MVP kan klare oss med en hurtigfiks som bare krymper alt så man ser alt på en side, og så får man heller zoome med fingrene?

**Comment by xivind** [comment]
Lagt inn en hurtigfiks som skal vise alt på en side, men da må mobilbrukere zoome. Resultatfilen må generes på nytt for at det skal begynne å virke. Det er visst ikke en bra måte å gjøre det på, men kanskje godt nok for MVP?

**Comment by thomiz** [comment]
Løst ved oppdatering av websiden.
