### ISSUE TITLE
Legg til feilhåndtering og enkel logging i databehandler.py

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#7]
Vi ønsker å vite om noe har crashet, og siden det ikke logges noe til konsoll, kan vi lage noe enkelt som skriver resultat fra kjøringen og evt feil til en loggfil.

**Comment by thomiz** [comment]
Må håndtere blank moving_time

**Comment by xivind** [comment]
Se samtidig på funksjonen for regning av tid, division by zero

**Comment by xivind** [comment]
Feilhåndtering i databehandler forsøkt løst med [f354346](https://github.com/hdir/strava-club/commit/f354346c9ce6c687dbeefcd863dbe0f24484084d)

**Comment by xivind** [comment]
> Se samtidig på funksjonen for regning av tid, division by zero

Forsøkt løst med [99e66f3](https://github.com/hdir/strava-club/commit/99e66f3c6e37f287a602054164cf82033337c14f) Dette gjelder tidsfunksjonen i presentator

**Comment by xivind** [comment]
Klar for review!

**Comment by thomiz** [comment]
Don't seem to work [run](https://github.com/hdir/strava-club/actions/runs/8252465074/job/22572021565)

**Comment by xivind** [comment]
Sannelig! Feilkontrollen var på plass, men i mellomtiden har jeg introdusert en annen feil et annet sted (#2 ) som gjør at scriptet crasher hver gang. Trodde det var så enkelt at jeg ikke trengte å teste. Gjør ikke den feilen igjen :) Nå er det hvert fall fikset med [0670d41](https://github.com/hdir/strava-club/commit/0670d415f6e3131f1032721ff1525bfa63f2b78b) Klar til review igjen!

**Comment by thomiz** [comment]
Kjører fint nå!
Skal sjekke om det også kjører med flere klubber i input.

**Comment by thomiz** [comment]
Ser ut til å fungere fint, resultatet ligger i test branch, så den bør nok ikke merges med main for da får vi plutselig inn mange resultater vi ikke vil ha med :-)

[Resultater på web](https://hdir.github.io/strava-club/TestBuild/results.html)

**Comment by xivind** [comment]
Kult at det funket nå! Det vil si det, crasher hvert fall ikke, men optimalt er det ikke, ettersom det ser ut som de som er hentet fra sykkel-klubber jukser, siden tiden står til 00:00. Uansett, enig med deg, denne issuen er løst og vel så det. Så får vi si som et krav at koden forutsetter multisport.
