### ISSUE TITLE
Flere datafelter i aggregert oversikt for hele klubben

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#8]
I oversikten over resultater for klubben samlet vil vi også se:

- [x] Antall aktive deltakere
- [x] Antall aktiviteter
- [x] Spart CO2 (kanskje), basert i så fall på en troverdig kilde

**Comment by xivind** [comment]
@thomiz da er de tre datafeltene over lagt til. Beregningen av CO2 er basert på https://ecf.com/news-and-events/news/how-much-co2-does-cycling-really-save Bør vi nevne det noe, f. eks. på informasjonssiden, slik at vi ikke mistenkes for grønnvasking og fri fantasi..? Rokkerte også litt på rekkefølgen så det skulle virke mer logisk. Hva synes du? Klar for review!

**Comment by thomiz** [comment]
Nå fungerer den.
