### ISSUE TITLE
Refaktorer presentator.py

### ISSUE THREAD

**Issue by xivind** [hdir/strava-club#9]
Mye småtteri som bør justeres for å gjøre koden mer håndterbar

**Comment by xivind** [comment]
Innarbeid samtidig feilhåndtering

**Comment by xivind** [comment]
Setter denne til middels prioritering. Mye av funksjonaliteten vi ønsker oss må gjøres her, og det blir stadig mer komplisert å jobbe i filen siden den er så rotete.

**Comment by xivind** [comment]
@thomiz det vil gjøre #29 #33 og #34 sinnsykt mye enklere dersom presentator er objektorientert, som er formålet med refaktoreringen. Jeg setter i gang. Tror faktisk ikke det vil ta så lang tid, og vi kommer til å spare det inn etterpå når vi løser oppgaven nevnt i forrige setning.

**Comment by xivind** [comment]
Ny versjon underveis, objektorientert med tanke på at den under main-seksjonen senere kan utvides med noen løkker for å håndtere resultater pr. lag. I første versjon vil den ikke håndtere lag, men skal senere relativt enkelt kunne utvides til å gjøre det.

**Comment by xivind** [comment]
Dette var faktisk ganske tidkrevende, men jeg tror det har blitt veldig bra, og jeg tror vi får igjen for dette siden, dersom vi vil gjøre mer med presentator! Veldig ønskelig med et godt og kritisk blikk fra deg @thomiz . Men det kan hende at det kan skje gjennom simuleringen vår #29 , og at denne saken derfor kan lukkes. Siste versjon er hvert fall dyttet til repoet og jeg kunne egentlig godt tenkt meg at vi begynner å bruke V2 fremover fremfor den gamle funksjonsorienterte. Om du synes det er ok?

**Comment by thomiz** [comment]
Da er v2 i produksjon.
